services:
  catalogdb:
    image: postgres:latest

  basketdb:
    image: postgres:latest

  catalogapi:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/CatalogAPI/Dockerfile

volumes:
  postgres_catalog:
  postgres_basket:
