services:
  catalogdb:
    image: postgres:latest

  basketdb:
    image: postgres:latest

  distributedcache:
    image: redis:latest

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

  discount.grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    volumes:
      - discount-sqlite-data:/app/files
    build:
      context: .
      dockerfile: Services/Discount/Discount.Grpc/Dockerfile

volumes:
  postgres_catalog:
  postgres_basket:
  discount-sqlite-data:


